// ---------------------------------------------------------------------------
// Default Professions Taxonomy Seed Data
// Universal domain professions + custom role support
// ---------------------------------------------------------------------------

export const DEFAULT_CATEGORIES = [
  {
    name: 'Technology & Software',
    slug: 'technology-software',
    icon: 'code',
    displayOrder: 1,
    professions: [
      {
        name: 'Engineer',
        subtitle: 'Universal Engineering: Software, Systems, Cloud, AI, DevOps & Security',
        aliases: [
          'software engineer',
          'developer',
          'frontend',
          'frontend developer',
          'backend',
          'backend developer',
          'full stack',
          'full stack developer',
          'mobile developer',
          'web developer',
          'devops',
          'cloud engineer',
          'data scientist',
          'data & ai engineer',
          'ai engineer',
          'machine learning engineer',
          'cybersecurity engineer',
          'cybersecurity specialist',
          'qa engineer',
          'software architect',
          'engineering',
          'programmer',
          'coder',
          'systems engineer',
          'hardware engineer',
        ],
        recommendedSectionTypes: ['skills', 'projects', 'experience', 'certifications', 'education'],
      },
    ],
  },
  {
    name: 'Healthcare & Medicine',
    slug: 'healthcare-medicine',
    icon: 'activity',
    displayOrder: 2,
    professions: [
      {
        name: 'Doctor / Healthcare Professional',
        subtitle: 'Universal Medical: Physicians, Dentists, Clinicians, Specialists & Surgeons',
        aliases: [
          'doctor',
          'physician',
          'medical doctor',
          'dentist',
          'surgeon',
          'nurse',
          'pharmacist',
          'specialist',
          'clinician',
          'clinical psychologist',
          'medical researcher',
          'physiotherapist',
        ],
        recommendedSectionTypes: ['education', 'experience', 'services', 'certifications', 'publications'],
      },
    ],
  },
  {
    name: 'Business & Entrepreneurship',
    slug: 'business-entrepreneurship',
    icon: 'briefcase',
    displayOrder: 3,
    professions: [
      {
        name: 'Founder / Entrepreneur',
        subtitle: 'Universal Business: Founders, CEOs, Executives, Consultants & Strategists',
        aliases: [
          'founder',
          'entrepreneur',
          'ceo',
          'executive',
          'business consultant',
          'business analyst',
          'product manager',
          'product & tech manager',
          'freelancer',
          'strategist',
          'director',
          'consultant',
        ],
        recommendedSectionTypes: ['organizations', 'experience', 'services', 'awards', 'projects'],
      },
    ],
  },
  {
    name: 'Design & Creative',
    slug: 'design-creative',
    icon: 'palette',
    displayOrder: 4,
    professions: [
      {
        name: 'Creator & Designer',
        subtitle: 'Universal Creative: Content Creators, Designers, Artists, Writers & Media',
        aliases: [
          'creator',
          'content creator',
          'designer',
          'ui/ux designer',
          'product designer',
          'graphic designer',
          'brand designer',
          'artist',
          'writer',
          'copywriter',
          'photographer',
          '3d designer',
          'media',
          'video creator',
        ],
        recommendedSectionTypes: ['mediaGallery', 'projects', 'services', 'skills', 'awards'],
      },
    ],
  },
  {
    name: 'Education & Academia',
    slug: 'education-academia',
    icon: 'graduation-cap',
    displayOrder: 5,
    professions: [
      {
        name: 'Student & Academic',
        subtitle: 'Universal Academic: Students, University Scholars, Professors & Researchers',
        aliases: [
          'student',
          'university student',
          'college student',
          'graduate scholar',
          'professor',
          'faculty',
          'teacher',
          'educator',
          'lecturer',
          'academic researcher',
          'researcher',
          'scholar',
          'medical resident',
        ],
        recommendedSectionTypes: ['education', 'projects', 'skills', 'certifications', 'research'],
      },
    ],
  },
];
